In [1]:
import pandas as pd

In [2]:
# Read the data into a Pandas DataFrame
crowdfunding_data = pd.ExcelFile("crowdfunding.xlsx")
# Get the sheet names.
crowdfunding_data.sheet_names

['crowdfunding_info', 'contact_info']

In [3]:
# Get the crowdfunding_info from the crowdfunding_info worksheet. 
crowdfunding_info_df = pd.read_excel(crowdfunding_data, sheet_name='crowdfunding_info')
crowdfunding_info_df.head()

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock
4,1365,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays

In [4]:
# Get the contact_info from the contact_info worksheet.
# Increase the width of the column.
pd.set_option('max_colwidth', 400)
contact_info_df = pd.read_excel(crowdfunding_data, sheet_name='contact_info', header=2)
contact_info_df.head()

0                                                                               contact_info
1   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
2          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
3            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
4  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}

In [5]:
# Get a brief summary of the crowdfunding_info DataFrame. 
crowdfunding_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cf_id                    1000 non-null   int64
 1   company_name             1000 non-null   object
 2   blurb                    1000 non-null   object
 3   goal                     1000 non-null   int64
 4   pledged                  1000 non-null   int64
 5   outcome                  1000 non-null   object
 6   backers_count            1000 non-null   int64
 7   country                  1000 non-null   object
 8   currency                 1000 non-null   object
 9   launched_at              1000 non-null   int64
 10  deadline                 1000 non-null   int64
 11  staff_pick               1000 non-null   bool
 12  spotlight                1000 non-null   bool
 13  category & sub-category  1000 non-null   object
dtypes: bool(2), int64(6), object(6)
memory usage: 95.8+ KB

In [6]:
# Get a brief summary of the contact_info DataFrame. 
contact_info_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0           1001 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [7]:
# Get the unique values in the category & sub-category column. 
crowdfunding_info_df["category & sub-category"].unique()

array(['food/food trucks', 'music/rock', 'technology/web',
       'theater/plays', 'film & video/documentary',
       'music/electric music', 'film & video/drama', 'music/indie rock',
       'technology/wearables', 'publishing/nonfiction',
       'film & video/animation', 'games/video games',
       'film & video/shorts', 'publishing/fiction',
       'photography/photography books', 'publishing/radio & podcasts',
       'music/metal', 'music/jazz', 'publishing/translations',
       'film & video/television', 'games/mobile games',
       'music/world music', 'film & video/science fiction',
       'journalism/audio'], dtype=object)

In [8]:
# Assign the category and subcategory values to category and subcategory columns.
crowdfunding_info_df[["category","subcategory"]] = crowdfunding_info_df["category & sub-category"].str.split('/', n=1, expand=True)
crowdfunding_info_df.head(10)

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays
5,2057,Harris Group,Open-source optimizing database,7600,13195,successful,174,DK,DKK,1607666400,1630213200,False,False,theater/plays,theater,plays
6,1894,"Ortiz, Coleman and Mitchell",Operative upward-trending algorithm,5200,1090,failed,18,GB,GBP,1596171600,1620709200,False,False,film & video/documentary,film & video,documentary
7,2669,Carter-Guzman,Centralized cohesive challenge,4500,14741,successful,227,DK,DKK,1608616800,1632200400,False,False,theater/plays,theater,plays
8,1114,Nunez-Richards,Exclusive attitude-oriented intranet,110100,21946,live,708,DK,DKK,1586322000,1615356000,False,False,theater/plays,theater,plays
9,970,"Rangel, Holt and Jones",Open-source fresh-thinking model,6200,3208,failed,44,US,USD,1628830800,1630386000,False,False,music/electric music,music,electric music

In [9]:
# Get the distinct values in the category and subcategory columns.
print(crowdfunding_info_df["category"].nunique())
print(crowdfunding_info_df["subcategory"].nunique())

9
24

In [10]:
# Get the unique categories and subcategories in separate lists.
categories = crowdfunding_info_df["category"].unique()
subcategories = crowdfunding_info_df["subcategory"].unique()
print(categories)
print()
print(subcategories)

['food' 'music' 'technology' 'theater' 'film & video' 'publishing' 'games'
 'photography' 'journalism']

['food trucks' 'rock' 'web' 'plays' 'documentary' 'electric music' 'drama'
 'indie rock' 'wearables' 'nonfiction' 'animation' 'video games' 'shorts'
 'fiction' 'photography books' 'radio & podcasts' 'metal' 'jazz'
 'translations' 'television' 'mobile games' 'world music'
 'science fiction' 'audio']

In [13]:
##plan
# Import the Numpy dependency
import numpy as np

# Create numpy arrays that have 1-10 for the category_ids and 1-25 for the subcategory_ids.
category_ids = np.arange(1, 10)
subcategory_ids = np.arange(1, 25)

In [14]:
# Use a list comprehension to add "cat0" to each category_id. 
cat_ids = ["cat0" + str(cat_id) for cat_id in category_ids]

# Use a list comprehension to add "scat0" to each subcategory_id. 
scat_ids = ["scat0" + str(scat_id) for scat_id in subcategory_ids ]

print(cat_ids)
print(scat_ids)

['cat01', 'cat02', 'cat03', 'cat04', 'cat05', 'cat06', 'cat07', 'cat08', 'cat09']
['scat01', 'scat02', 'scat03', 'scat04', 'scat05', 'scat06', 'scat07', 'scat08', 'scat09', 'scat010', 'scat011', 'scat012', 'scat013', 'scat014', 'scat015', 'scat016', 'scat017', 'scat018', 'scat019', 'scat020', 'scat021', 'scat022', 'scat023', 'scat024']

In [15]:
# Create a category DataFrame with the cat_ids array as the category_id and categories list as the category name.
category_df = pd.DataFrame({
    "category_id": cat_ids,
    "category" : categories
})

# Create a subcategory DataFrame with the scat_ids array as the subcategory_id and subcategories list as the subcategory name.
subcategory_df = pd.DataFrame({
    "subcategory_id": scat_ids,
    "subcategory" : subcategories
})

In [21]:
#export to csv
subcategory_df.to_csv('file.csv', index=False)
category_df.to_csv('file.csv', index=False)

In [22]:
##PLAN
# Create a copy of the crowdfunding_info_df DataFrame name campaign_df.
campaign_df = crowdfunding_info_df.copy()
campaign_df.head()

,cf_id,company_name,blurb,goal,pledged,outcome,backers_count,country,currency,launched_at,deadline,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100,0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400,14560,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400,142523,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200,2477,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600,5265,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [23]:
# Rename the blurb, launched_at, and deadline columns.
campaign_df = campaign_df.rename(columns={'blurb': 'description', 'launched_at': 'launched_date', 'deadline': 'end_date'})

In [24]:
# Convert the goal and pledged columns to a `float` data type.
campaign_df[["goal","pledged"]] = campaign_df[["goal","pledged"]].astype(float)
campaign_df.head()

,cf_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,1581573600,1614578400,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,1611554400,1621918800,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,1608184800,1640844000,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,1634792400,1642399200,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,1608530400,1629694800,False,False,theater/plays,theater,plays

In [25]:
# Format the launched_date and end_date columns to datetime format.
from datetime import datetime as dt
campaign_df["launched_date"] = pd.to_datetime(campaign_df["launched_date"], unit='s').dt.strftime('%Y-%m-%d') 
campaign_df["end_date"] = pd.to_datetime(campaign_df["end_date"], unit='s').dt.strftime('%Y-%m-%d')
campaign_df.head()

,cf_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,2020-02-13,2021-03-01,False,False,food/food trucks,food,food trucks
1,1621,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,2021-01-25,2021-05-25,False,True,music/rock,music,rock
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,2020-12-17,2021-12-30,False,False,technology/web,technology,web
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,2021-10-21,2022-01-17,False,False,music/rock,music,rock
4,1365,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,2020-12-21,2021-08-23,False,False,theater/plays,theater,plays

In [38]:
# Merge the campaign_df with the category_df on the "category" column and 
# the subcategory_df on the "subcategory" column.
campaign_merged_df = campaign_df.merge(category_df, on='category', how='left').merge(subcategory_df, on='subcategory', how='left')
campaign_merged_df.tail(10)

,cf_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,staff_pick,spotlight,category & sub-category,category,subcategory,category_id,subcategory_id
990,1561,Ortiz-Roberts,Devolved foreground customer loyalty,7800.0,6839.0,failed,64,US,USD,2021-06-09,2021-06-18,False,True,film & video/drama,film & video,drama,cat05,scat07
991,2632,Ramirez LLC,Reduced reciprocal focus group,9800.0,11091.0,successful,241,US,USD,2020-12-09,2021-05-26,False,True,music/rock,music,rock,cat02,scat02
992,439,Morrow Inc,Networked global migration,3100.0,13223.0,successful,132,US,USD,2020-06-14,2021-02-09,False,True,film & video/drama,film & video,drama,cat05,scat07
993,461,Erickson-Rogers,De-engineered even-keeled definition,9800.0,7608.0,canceled,75,IT,EUR,2021-07-03,2021-07-08,False,True,photography/photography books,photography,photography books,cat08,scat015
994,1419,"Leach, Rich and Price",Implemented bi-directional flexibility,141100.0,74073.0,failed,842,US,USD,2021-11-15,2021-12-07,False,True,publishing/translations,publishing,translations,cat06,scat019
995,2986,Manning-Hamilton,Vision-oriented scalable definition,97300.0,153216.0,successful,2043,US,USD,2020-12-29,2021-05-30,False,True,food/food trucks,food,food trucks,cat01,scat01
996,2031,Butler LLC,Future-proofed upward-trending migration,6600.0,4814.0,failed,112,US,USD,2021-10-15,2021-11-30,False,False,theater/plays,theater,plays,cat04,scat04
997,1627,Ball LLC,Right-sized full-range throughput,7600.0,4603.0,canceled,139,IT,EUR,2021-11-06,2021-12-10,False,False,theater/plays,theater,plays,cat04,scat04
998,2175,"Taylor, Santiago and Flores",Polarized composite customer loyalty,66600.0,37823.0,failed,374,US,USD,2020-10-08,2021-04-11,False,True,music/indie rock,music,indie rock,cat02,scat08
999,1788,"Hernandez, Norton and Kelley",Expanded eco-centric policy,111100.0,62819.0,canceled,1122,US,USD,2020-12-30,2021-08-18,False,False,food/food trucks,food,food trucks,cat01,scat01

In [50]:
# Drop unwanted columns.
campaign_cleaned = campaign_merged_df.drop(['staff_pick', 'spotlight', 'category & sub-category','category', 'subcategory'], axis=1)
campaign_cleaned.head()

,cf_id,company_name,description,goal,pledged,outcome,backers_count,country,currency,launched_date,end_date,category_id,subcategory_id
0,147,"Baldwin, Riley and Jackson",Pre-emptive tertiary standardization,100.0,0.0,failed,0,CA,CAD,2020-02-13,2021-03-01,cat01,scat01
1,1621,Odom Inc,Managed bottom-line architecture,1400.0,14560.0,successful,158,US,USD,2021-01-25,2021-05-25,cat02,scat02
2,1812,"Melton, Robinson and Fritz",Function-based leadingedge pricing structure,108400.0,142523.0,successful,1425,AU,AUD,2020-12-17,2021-12-30,cat03,scat03
3,2156,"Mcdonald, Gonzalez and Ross",Vision-oriented fresh-thinking conglomeration,4200.0,2477.0,failed,24,US,USD,2021-10-21,2022-01-17,cat02,scat02
4,1365,Larson-Little,Proactive foreground core,7600.0,5265.0,failed,53,US,USD,2020-12-21,2021-08-23,cat04,scat04

In [51]:
# Show the contact_info_df DataFrame.
contact_info_df.head()

0                                                                               contact_info
1   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
2          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
3            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
4  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}

In [52]:
# Retrieve the data from the "contact_info" column.
contact_info_list = contact_info_df.contact_info.to_list()
contact_info_list

AttributeError: 'DataFrame' object has no attribute 'contact_info'

In [47]:
# Pop out the unique identification number using list slicing. 
print(contact_info_list[0][:15])
print(contact_info_list[0][15:19])

NameError: name 'contact_info_list' is not defined

In [48]:
# Pop out the unique identification number using list comprehension and slicing. 
print([x[15:19] for x in contact_info_list])

NameError: name 'contact_info_list' is not defined

In [49]:
# Extract the four-digit contact ID number and add it to a new column in the `campaign_cleaned` DataFrame.
campaign_cleaned["contact_id"] = [x[15:19] for x in contact_info_df["contact_info"].values]
campaign_cleaned.head()

KeyError: 'contact_info'

In [53]:
# Convert the "contact_id" column to an int64 data type.
campaign_cleaned['contact_id'] = pd.to_numeric(campaign_cleaned['contact_id'])
campaign_cleaned.info()

KeyError: 'contact_id'

In [54]:
# Extract the four-digit contact ID number and add it to a new column in the contact_info DataFrame.
contact_info_df["contact_id"] = [x[15:19] for x in contact_info_df["contact_info"].values]
contact_info_df.head()

KeyError: 'contact_info'

In [55]:
# Get the data from the first row and convert it to a dictionary.
import json
first_row = contact_info_df.iloc[0]['contact_info']
converted_data = json.loads(first_row)
for k, v in converted_data.items():
    print(k,v)

KeyError: 'contact_info'

In [56]:
# Iterate through the contact_info_df and convert each row to a dictionary.
dict_values = []
for i, row in contact_info_df.iterrows():
    # Get the data first item in each row.
    data = row['contact_info']
    converted_data = json.loads(data)
    # Iterate through each dictionary (row) and get the values for each row using list comprehension.
    row_values = [v for k, v in converted_data.items()]
    # Append the list of values for each row to a new list. 
    dict_values.append(row_values)

# Print out the list of values for each row.
print(dict_values)

KeyError: 'contact_info'

In [57]:
# Create a contact_info DataFrame and add each list of values, i.e., each row to the 'contact_id', 'name', 'email' columns.
contacts_df = pd.DataFrame(dict_values, columns=['contact_id', 'name', 'email'])
contacts_df.head()

Empty DataFrame
Columns: [contact_id, name, email]
Index: []

In [58]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 
contacts_df[["first_name","last_name"]] = contacts_df["name"].str.split(' ', n=1, expand=True)

# Drop the name column. 
contacts_df_clean = contacts_df.drop(['name'], axis=1)
contacts_df_clean.head(10)

ValueError: Columns must be same length as key